[project]
name = "websockets"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "channels-redis>=4.2.1",
    "channels>=4.2.0",
    "daphne>=4.1.2",
    "django>=5.1.3",
]
